### ISSUE TITLE
Compilation error on MacOS

### ISSUE THREAD

**Issue by normen** [notedit/gstreamer-go#6]
Getting this error when trying to compile on MacOS 12.6 (Intel), GoLang 1.19.2
```
# github.com/notedit/gst
../../../go/pkg/mod/github.com/notedit/gst@v0.1.3/element_other.go:14:96: cannot use _Ctype_long(duration.Nanoseconds()) (value of type _Ctype_long) as type _Ctype_longlong in variable declaration
make: *** [build] Error 2
```
